os: linux
dist: bionic
language: java
install: true


addons:
  sonarcloud:
    organization: "trisquareeu"
    token: $sonarkey

script:
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

